#!/bin/bash
# terraform import n8n_credential_google_cloud_storage_oauth2_api.example {credential_id}
terraform import n8n_credential_google_cloud_storage_oauth2_api.example REPLACE_WITH_CREDENTIAL_ID
