#!/bin/bash
# terraform import n8n_credential_microsoft_graph_security_oauth2_api.example {credential_id}
terraform import n8n_credential_microsoft_graph_security_oauth2_api.example REPLACE_WITH_CREDENTIAL_ID
